//! Fluent builders for the Identity module.
//!
//! This module provides ergonomic, type-safe fluent builders for the most
//! common identity operations. All builders follow the classic Builder
//! pattern and return the corresponding request type from `requests.rs`
//! for seamless integration with `TxBuilder`.

use alloc::string::String;
use alloc::vec::Vec;

use morpheum_sdk_core::SdkError;

use crate::requests::{
    RegisterAgentRequest,
    TransferOwnershipRequest,
    UpdateMetadataRequest,
    UpdateStatusRequest,
    BurnAgentRequest,
};
use crate::types::{AgentMetadataCardInput, AgentStatus};

// ====================== REGISTER AGENT ======================

/// Fluent builder for registering a new AI Agent.
///
/// # Example
/// ```rust,ignore
/// let request = RegisterAgentBuilder::new()
///     .owner_agent_hash("abc123…")
///     .metadata(AgentMetadataCardInput {
///         display_name: "TradeBot".into(),
///         version: "1.0.0".into(),
///         ..Default::default()
///     })
///     .owner_signature(sig_bytes)
///     .capabilities(Capability::TRADE | Capability::EVALUATE)
///     .build()?;
/// ```
#[derive(Default)]
pub struct RegisterAgentBuilder {
    did: Option<String>,
    owner_agent_hash: Option<String>,
    metadata: Option<AgentMetadataCardInput>,
    owner_signature: Option<Vec<u8>>,
    capabilities: u64,
    self_owned: bool,
    initial_vc: Option<Vec<u8>>,
}

impl RegisterAgentBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets an explicit DID (otherwise auto-generated by the keeper).
    pub fn did(mut self, did: impl Into<String>) -> Self {
        self.did = Some(did.into());
        self
    }

    /// Sets the owner's agent hash.
    pub fn owner_agent_hash(mut self, hash: impl Into<String>) -> Self {
        self.owner_agent_hash = Some(hash.into());
        self
    }

    /// Sets the agent's metadata.
    pub fn metadata(mut self, metadata: AgentMetadataCardInput) -> Self {
        self.metadata = Some(metadata);
        self
    }

    /// Sets the owner's signature.
    pub fn owner_signature(mut self, sig: Vec<u8>) -> Self {
        self.owner_signature = Some(sig);
        self
    }

    /// Sets the initial capability bitflags.
    pub fn capabilities(mut self, caps: u64) -> Self {
        self.capabilities = caps;
        self
    }

    /// Marks the agent as self-owned (autonomous).
    pub fn self_owned(mut self, val: bool) -> Self {
        self.self_owned = val;
        self
    }

    /// Attaches an initial VC for immediate delegation.
    pub fn initial_vc(mut self, vc_bytes: Vec<u8>) -> Self {
        self.initial_vc = Some(vc_bytes);
        self
    }

    /// Builds the registration request, performing validation.
    pub fn build(self) -> Result<RegisterAgentRequest, SdkError> {
        let owner_agent_hash = self.owner_agent_hash.ok_or_else(|| {
            SdkError::invalid_input("owner_agent_hash is required for registration")
        })?;

        let metadata = self.metadata.ok_or_else(|| {
            SdkError::invalid_input("metadata is required for registration")
        })?;

        let owner_signature = self.owner_signature.ok_or_else(|| {
            SdkError::invalid_input("owner_signature is required for registration")
        })?;

        let mut req = RegisterAgentRequest::new(owner_agent_hash, metadata, owner_signature);
        req.did = self.did;
        req.capabilities = self.capabilities;
        req.self_owned = self.self_owned;
        req.initial_vc = self.initial_vc;

        Ok(req)
    }
}

// ====================== TRANSFER OWNERSHIP ======================

/// Fluent builder for transferring ownership of an agent.
#[derive(Default)]
pub struct TransferOwnershipBuilder {
    agent_hash: Option<String>,
    new_owner_agent_hash: Option<String>,
    current_owner_signature: Option<Vec<u8>>,
}

impl TransferOwnershipBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn agent_hash(mut self, hash: impl Into<String>) -> Self {
        self.agent_hash = Some(hash.into());
        self
    }

    pub fn new_owner_agent_hash(mut self, hash: impl Into<String>) -> Self {
        self.new_owner_agent_hash = Some(hash.into());
        self
    }

    pub fn current_owner_signature(mut self, sig: Vec<u8>) -> Self {
        self.current_owner_signature = Some(sig);
        self
    }

    pub fn build(self) -> Result<TransferOwnershipRequest, SdkError> {
        let agent_hash = self.agent_hash.ok_or_else(|| {
            SdkError::invalid_input("agent_hash is required for ownership transfer")
        })?;

        let new_owner_agent_hash = self.new_owner_agent_hash.ok_or_else(|| {
            SdkError::invalid_input("new_owner_agent_hash is required for ownership transfer")
        })?;

        let current_owner_signature = self.current_owner_signature.ok_or_else(|| {
            SdkError::invalid_input("current_owner_signature is required for ownership transfer")
        })?;

        Ok(TransferOwnershipRequest::new(
            agent_hash,
            new_owner_agent_hash,
            current_owner_signature,
        ))
    }
}

// ====================== UPDATE METADATA ======================

/// Fluent builder for updating agent metadata.
#[derive(Default)]
pub struct UpdateMetadataBuilder {
    agent_hash: Option<String>,
    new_metadata: Option<AgentMetadataCardInput>,
    owner_signature: Option<Vec<u8>>,
}

impl UpdateMetadataBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn agent_hash(mut self, hash: impl Into<String>) -> Self {
        self.agent_hash = Some(hash.into());
        self
    }

    pub fn new_metadata(mut self, metadata: AgentMetadataCardInput) -> Self {
        self.new_metadata = Some(metadata);
        self
    }

    pub fn owner_signature(mut self, sig: Vec<u8>) -> Self {
        self.owner_signature = Some(sig);
        self
    }

    pub fn build(self) -> Result<UpdateMetadataRequest, SdkError> {
        let agent_hash = self.agent_hash.ok_or_else(|| {
            SdkError::invalid_input("agent_hash is required for metadata update")
        })?;

        let new_metadata = self.new_metadata.ok_or_else(|| {
            SdkError::invalid_input("new_metadata is required for metadata update")
        })?;

        let owner_signature = self.owner_signature.ok_or_else(|| {
            SdkError::invalid_input("owner_signature is required for metadata update")
        })?;

        Ok(UpdateMetadataRequest::new(agent_hash, new_metadata, owner_signature))
    }
}

// ====================== UPDATE STATUS ======================

/// Fluent builder for updating agent status (suspend, slash, etc.).
#[derive(Default)]
pub struct UpdateStatusBuilder {
    agent_hash: Option<String>,
    new_status: Option<AgentStatus>,
    signature: Option<Vec<u8>>,
    reason: Option<String>,
}

impl UpdateStatusBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn agent_hash(mut self, hash: impl Into<String>) -> Self {
        self.agent_hash = Some(hash.into());
        self
    }

    pub fn new_status(mut self, status: AgentStatus) -> Self {
        self.new_status = Some(status);
        self
    }

    pub fn signature(mut self, sig: Vec<u8>) -> Self {
        self.signature = Some(sig);
        self
    }

    pub fn reason(mut self, reason: impl Into<String>) -> Self {
        self.reason = Some(reason.into());
        self
    }

    pub fn build(self) -> Result<UpdateStatusRequest, SdkError> {
        let agent_hash = self.agent_hash.ok_or_else(|| {
            SdkError::invalid_input("agent_hash is required for status update")
        })?;

        let new_status = self.new_status.ok_or_else(|| {
            SdkError::invalid_input("new_status is required for status update")
        })?;

        let signature = self.signature.ok_or_else(|| {
            SdkError::invalid_input("signature is required for status update")
        })?;

        let mut req = UpdateStatusRequest::new(agent_hash, new_status, signature);
        req.reason = self.reason;
        Ok(req)
    }
}

// ====================== BURN AGENT ======================

/// Fluent builder for burning an agent (governance only).
#[derive(Default)]
pub struct BurnAgentBuilder {
    agent_hash: Option<String>,
    gov_signature: Option<Vec<u8>>,
    reason: Option<String>,
}

impl BurnAgentBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn agent_hash(mut self, hash: impl Into<String>) -> Self {
        self.agent_hash = Some(hash.into());
        self
    }

    pub fn gov_signature(mut self, sig: Vec<u8>) -> Self {
        self.gov_signature = Some(sig);
        self
    }

    pub fn reason(mut self, reason: impl Into<String>) -> Self {
        self.reason = Some(reason.into());
        self
    }

    pub fn build(self) -> Result<BurnAgentRequest, SdkError> {
        let agent_hash = self.agent_hash.ok_or_else(|| {
            SdkError::invalid_input("agent_hash is required for burn")
        })?;

        let gov_signature = self.gov_signature.ok_or_else(|| {
            SdkError::invalid_input("gov_signature is required for burn")
        })?;

        let mut req = BurnAgentRequest::new(agent_hash, gov_signature);
        req.reason = self.reason;
        Ok(req)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    #[test]
    fn register_builder_full_flow() {
        let metadata = AgentMetadataCardInput {
            display_name: "TestAgent".into(),
            description: "A test agent".into(),
            tags: "test".into(),
            version: "1.0.0".into(),
            capabilities: 1,
        };

        let req = RegisterAgentBuilder::new()
            .owner_agent_hash("owner_hash")
            .metadata(metadata)
            .owner_signature(vec![0u8; 64])
            .did("did:agent:test")
            .capabilities(3)
            .self_owned(true)
            .build()
            .unwrap();

        assert_eq!(req.owner_agent_hash, "owner_hash");
        assert_eq!(req.did, Some("did:agent:test".into()));
        assert!(req.self_owned);
        assert_eq!(req.capabilities, 3);
    }

    #[test]
    fn register_builder_minimal() {
        let req = RegisterAgentBuilder::new()
            .owner_agent_hash("owner")
            .metadata(AgentMetadataCardInput::default())
            .owner_signature(vec![])
            .build()
            .unwrap();

        assert!(req.did.is_none());
        assert!(!req.self_owned);
        assert_eq!(req.capabilities, 0);
        assert!(req.initial_vc.is_none());
    }

    #[test]
    fn register_builder_validation() {
        let result = RegisterAgentBuilder::new().build();
        assert!(result.is_err());
    }

    #[test]
    fn transfer_builder_works() {
        let req = TransferOwnershipBuilder::new()
            .agent_hash("agent1")
            .new_owner_agent_hash("owner2")
            .current_owner_signature(vec![0u8; 64])
            .build()
            .unwrap();

        assert_eq!(req.agent_hash, "agent1");
        assert_eq!(req.new_owner_agent_hash, "owner2");
    }

    #[test]
    fn transfer_builder_validation() {
        let result = TransferOwnershipBuilder::new().build();
        assert!(result.is_err());
    }

    #[test]
    fn update_metadata_builder_works() {
        let metadata = AgentMetadataCardInput {
            display_name: "Updated".into(),
            ..Default::default()
        };

        let req = UpdateMetadataBuilder::new()
            .agent_hash("agent1")
            .new_metadata(metadata)
            .owner_signature(vec![0u8; 64])
            .build()
            .unwrap();

        assert_eq!(req.agent_hash, "agent1");
        assert_eq!(req.new_metadata.display_name, "Updated");
    }

    #[test]
    fn update_status_builder_works() {
        let req = UpdateStatusBuilder::new()
            .agent_hash("agent1")
            .new_status(AgentStatus::Suspended)
            .signature(vec![0u8; 64])
            .reason("testing")
            .build()
            .unwrap();

        assert_eq!(req.agent_hash, "agent1");
        assert_eq!(req.new_status, AgentStatus::Suspended);
        assert_eq!(req.reason, Some("testing".into()));
    }

    #[test]
    fn update_status_builder_validation() {
        let result = UpdateStatusBuilder::new().build();
        assert!(result.is_err());
    }

    #[test]
    fn burn_builder_works() {
        let req = BurnAgentBuilder::new()
            .agent_hash("agent1")
            .gov_signature(vec![0u8; 64])
            .reason("governance decision")
            .build()
            .unwrap();

        assert_eq!(req.agent_hash, "agent1");
        assert_eq!(req.reason, Some("governance decision".into()));
    }

    #[test]
    fn burn_builder_validation() {
        let result = BurnAgentBuilder::new().build();
        assert!(result.is_err());
    }
}
