//! Request and response wrappers for the Identity module.
//!
//! These provide clean, type-safe Rust APIs around the raw protobuf messages.
//! They use idiomatic Rust types, offer ergonomic constructors, and include
//! `to_any()` methods for seamless integration with `TxBuilder`.

use alloc::string::String;
use alloc::vec::Vec;

use prost::Message as _;

#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

use morpheum_proto::google::protobuf::Any as ProtoAny;
use morpheum_proto::identity::v1 as proto;

use crate::types::{AgentMetadataCardInput, AgentStatus};

// ====================== TRANSACTION REQUESTS ======================

/// Request to register a new AI Agent identity.
///
/// The `did` field is optional — when `None`, the keeper auto-generates a
/// DID from `"did:agent:" + hex(SHA256(owner_agent_hash || timestamp))`.
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct RegisterAgentRequest {
    /// Optional DID — if `None`, the keeper auto-generates one.
    pub did: Option<String>,
    /// The owner's agent hash (initial owner of the new agent).
    pub owner_agent_hash: String,
    /// Metadata for the new agent.
    pub metadata: AgentMetadataCardInput,
    /// Signature proving ownership (over did + owner_agent_hash + metadata).
    pub owner_signature: Vec<u8>,
    /// Initial capability bitflags.
    pub capabilities: u64,
    /// If `true`, the new agent owns itself (autonomous agent).
    pub self_owned: bool,
    /// Optional initial VC bytes for immediate delegation.
    pub initial_vc: Option<Vec<u8>>,
}

impl RegisterAgentRequest {
    /// Creates a new registration request with required fields.
    pub fn new(
        owner_agent_hash: impl Into<String>,
        metadata: AgentMetadataCardInput,
        owner_signature: Vec<u8>,
    ) -> Self {
        Self {
            did: None,
            owner_agent_hash: owner_agent_hash.into(),
            metadata,
            owner_signature,
            capabilities: 0,
            self_owned: false,
            initial_vc: None,
        }
    }

    /// Sets an explicit DID (otherwise auto-generated by the keeper).
    #[must_use]
    pub fn with_did(mut self, did: impl Into<String>) -> Self {
        self.did = Some(did.into());
        self
    }

    /// Sets the initial capability bitflags.
    #[must_use]
    pub fn with_capabilities(mut self, caps: u64) -> Self {
        self.capabilities = caps;
        self
    }

    /// Marks the agent as self-owned (autonomous).
    #[must_use]
    pub fn self_owned(mut self) -> Self {
        self.self_owned = true;
        self
    }

    /// Attaches an initial VC for immediate delegation.
    #[must_use]
    pub fn with_initial_vc(mut self, vc_bytes: Vec<u8>) -> Self {
        self.initial_vc = Some(vc_bytes);
        self
    }

    /// Converts to a protobuf `Any` for `TxBuilder::add_message`.
    pub fn to_any(&self) -> ProtoAny {
        let msg: proto::MsgRegisterAgent = self.clone().into();
        ProtoAny {
            type_url: "/identity.v1.MsgRegisterAgent".into(),
            value: msg.encode_to_vec(),
        }
    }
}

impl From<RegisterAgentRequest> for proto::MsgRegisterAgent {
    fn from(req: RegisterAgentRequest) -> Self {
        Self {
            did: req.did,
            owner_agent_hash: req.owner_agent_hash,
            metadata: Some(req.metadata.into()),
            owner_signature: req.owner_signature,
            capabilities: req.capabilities,
            self_owned: req.self_owned,
            initial_vc: req.initial_vc,
        }
    }
}

/// Request to transfer ownership of an agent.
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct TransferOwnershipRequest {
    pub agent_hash: String,
    pub new_owner_agent_hash: String,
    pub current_owner_signature: Vec<u8>,
}

impl TransferOwnershipRequest {
    pub fn new(
        agent_hash: impl Into<String>,
        new_owner_agent_hash: impl Into<String>,
        current_owner_signature: Vec<u8>,
    ) -> Self {
        Self {
            agent_hash: agent_hash.into(),
            new_owner_agent_hash: new_owner_agent_hash.into(),
            current_owner_signature,
        }
    }

    pub fn to_any(&self) -> ProtoAny {
        let msg: proto::MsgTransferOwnership = self.clone().into();
        ProtoAny {
            type_url: "/identity.v1.MsgTransferOwnership".into(),
            value: msg.encode_to_vec(),
        }
    }
}

impl From<TransferOwnershipRequest> for proto::MsgTransferOwnership {
    fn from(req: TransferOwnershipRequest) -> Self {
        Self {
            agent_hash: req.agent_hash,
            new_owner_agent_hash: req.new_owner_agent_hash,
            current_owner_signature: req.current_owner_signature,
        }
    }
}

/// Request to update an agent's metadata.
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct UpdateMetadataRequest {
    pub agent_hash: String,
    pub new_metadata: AgentMetadataCardInput,
    pub owner_signature: Vec<u8>,
}

impl UpdateMetadataRequest {
    pub fn new(
        agent_hash: impl Into<String>,
        new_metadata: AgentMetadataCardInput,
        owner_signature: Vec<u8>,
    ) -> Self {
        Self {
            agent_hash: agent_hash.into(),
            new_metadata,
            owner_signature,
        }
    }

    pub fn to_any(&self) -> ProtoAny {
        let msg: proto::MsgUpdateMetadata = self.clone().into();
        ProtoAny {
            type_url: "/identity.v1.MsgUpdateMetadata".into(),
            value: msg.encode_to_vec(),
        }
    }
}

impl From<UpdateMetadataRequest> for proto::MsgUpdateMetadata {
    fn from(req: UpdateMetadataRequest) -> Self {
        Self {
            agent_hash: req.agent_hash,
            new_metadata: Some(req.new_metadata.into()),
            owner_signature: req.owner_signature,
        }
    }
}

/// Request to update an agent's status (suspend, slash, etc.).
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct UpdateStatusRequest {
    pub agent_hash: String,
    pub new_status: AgentStatus,
    pub owner_or_gov_signature: Vec<u8>,
    pub reason: Option<String>,
}

impl UpdateStatusRequest {
    pub fn new(
        agent_hash: impl Into<String>,
        new_status: AgentStatus,
        signature: Vec<u8>,
    ) -> Self {
        Self {
            agent_hash: agent_hash.into(),
            new_status,
            owner_or_gov_signature: signature,
            reason: None,
        }
    }

    /// Attaches a human-readable reason for the status change.
    #[must_use]
    pub fn with_reason(mut self, reason: impl Into<String>) -> Self {
        self.reason = Some(reason.into());
        self
    }

    pub fn to_any(&self) -> ProtoAny {
        let msg: proto::MsgUpdateStatus = self.clone().into();
        ProtoAny {
            type_url: "/identity.v1.MsgUpdateStatus".into(),
            value: msg.encode_to_vec(),
        }
    }
}

impl From<UpdateStatusRequest> for proto::MsgUpdateStatus {
    fn from(req: UpdateStatusRequest) -> Self {
        Self {
            agent_hash: req.agent_hash,
            new_status: req.new_status.to_proto(),
            owner_or_gov_signature: req.owner_or_gov_signature,
            reason: req.reason.unwrap_or_default(),
        }
    }
}

/// Request to permanently burn an agent (governance only).
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct BurnAgentRequest {
    pub agent_hash: String,
    pub gov_signature: Vec<u8>,
    pub reason: Option<String>,
}

impl BurnAgentRequest {
    pub fn new(
        agent_hash: impl Into<String>,
        gov_signature: Vec<u8>,
    ) -> Self {
        Self {
            agent_hash: agent_hash.into(),
            gov_signature,
            reason: None,
        }
    }

    /// Attaches a human-readable reason for the burn.
    #[must_use]
    pub fn with_reason(mut self, reason: impl Into<String>) -> Self {
        self.reason = Some(reason.into());
        self
    }

    pub fn to_any(&self) -> ProtoAny {
        let msg: proto::MsgBurnAgent = self.clone().into();
        ProtoAny {
            type_url: "/identity.v1.MsgBurnAgent".into(),
            value: msg.encode_to_vec(),
        }
    }
}

impl From<BurnAgentRequest> for proto::MsgBurnAgent {
    fn from(req: BurnAgentRequest) -> Self {
        Self {
            agent_hash: req.agent_hash,
            gov_signature: req.gov_signature,
            reason: req.reason.unwrap_or_default(),
        }
    }
}

// ====================== QUERY REQUESTS ======================

/// Query an agent identity by hash or DID.
///
/// Use the named constructors `by_hash()` or `by_did()` for clarity.
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct QueryAgentRequest {
    pub agent_hash: String,
    pub did: String,
}

impl QueryAgentRequest {
    /// Lookup by agent hash.
    pub fn by_hash(agent_hash: impl Into<String>) -> Self {
        Self {
            agent_hash: agent_hash.into(),
            did: String::new(),
        }
    }

    /// Lookup by DID string.
    pub fn by_did(did: impl Into<String>) -> Self {
        Self {
            agent_hash: String::new(),
            did: did.into(),
        }
    }
}

impl From<QueryAgentRequest> for proto::QueryAgentRequest {
    fn from(req: QueryAgentRequest) -> Self {
        Self {
            agent_hash: req.agent_hash,
            did: req.did,
        }
    }
}

/// Query all agents owned by a specific owner (paginated).
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct QueryAgentByOwnerRequest {
    pub owner_agent_hash: String,
    pub limit: u32,
    pub offset: u32,
}

impl QueryAgentByOwnerRequest {
    pub fn new(owner_agent_hash: impl Into<String>, limit: u32, offset: u32) -> Self {
        Self {
            owner_agent_hash: owner_agent_hash.into(),
            limit,
            offset,
        }
    }
}

impl From<QueryAgentByOwnerRequest> for proto::QueryAgentByOwnerRequest {
    fn from(req: QueryAgentByOwnerRequest) -> Self {
        Self {
            owner_agent_hash: req.owner_agent_hash,
            limit: req.limit,
            offset: req.offset,
        }
    }
}

/// Query the metadata card for an agent.
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct QueryMetadataCardRequest {
    pub agent_hash: String,
}

impl QueryMetadataCardRequest {
    pub fn new(agent_hash: impl Into<String>) -> Self {
        Self {
            agent_hash: agent_hash.into(),
        }
    }
}

impl From<QueryMetadataCardRequest> for proto::QueryMetadataCardRequest {
    fn from(req: QueryMetadataCardRequest) -> Self {
        Self {
            agent_hash: req.agent_hash,
        }
    }
}

/// Query the status of an agent.
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct QueryAgentStatusRequest {
    pub agent_hash: String,
}

impl QueryAgentStatusRequest {
    pub fn new(agent_hash: impl Into<String>) -> Self {
        Self {
            agent_hash: agent_hash.into(),
        }
    }
}

impl From<QueryAgentStatusRequest> for proto::QueryAgentStatusRequest {
    fn from(req: QueryAgentStatusRequest) -> Self {
        Self {
            agent_hash: req.agent_hash,
        }
    }
}

/// Query the current module parameters.
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct QueryParamsRequest;

impl From<QueryParamsRequest> for proto::QueryParamsRequest {
    fn from(_req: QueryParamsRequest) -> Self {
        Self {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    #[test]
    fn register_request_to_any() {
        let metadata = AgentMetadataCardInput {
            display_name: "TestAgent".into(),
            description: "Test".into(),
            ..Default::default()
        };

        let req = RegisterAgentRequest::new("owner_hash", metadata, vec![0u8; 64])
            .with_did("did:agent:test")
            .with_capabilities(3)
            .self_owned();

        let any = req.to_any();
        assert_eq!(any.type_url, "/identity.v1.MsgRegisterAgent");
        assert!(!any.value.is_empty());
    }

    #[test]
    fn register_request_auto_did() {
        let metadata = AgentMetadataCardInput::default();
        let req = RegisterAgentRequest::new("owner", metadata, vec![]);
        assert!(req.did.is_none());
    }

    #[test]
    fn transfer_request_to_any() {
        let req = TransferOwnershipRequest::new("agent_hash", "new_owner", vec![0u8; 64]);
        let any = req.to_any();
        assert_eq!(any.type_url, "/identity.v1.MsgTransferOwnership");
        assert!(!any.value.is_empty());
    }

    #[test]
    fn update_status_with_reason() {
        let req = UpdateStatusRequest::new("hash", AgentStatus::Suspended, vec![0u8; 64])
            .with_reason("misconduct");
        let proto: proto::MsgUpdateStatus = req.into();
        assert_eq!(proto.reason, "misconduct");
        assert_eq!(proto.new_status, AgentStatus::Suspended.to_proto());
    }

    #[test]
    fn burn_request_to_any() {
        let req = BurnAgentRequest::new("hash", vec![0u8; 64])
            .with_reason("governance decision");
        let any = req.to_any();
        assert_eq!(any.type_url, "/identity.v1.MsgBurnAgent");
        assert!(!any.value.is_empty());
    }

    #[test]
    fn query_agent_by_hash() {
        let req = QueryAgentRequest::by_hash("abc123");
        assert_eq!(req.agent_hash, "abc123");
        assert!(req.did.is_empty());
    }

    #[test]
    fn query_agent_by_did() {
        let req = QueryAgentRequest::by_did("did:agent:abc123");
        assert!(req.agent_hash.is_empty());
        assert_eq!(req.did, "did:agent:abc123");
    }

    #[test]
    fn query_by_owner_conversion() {
        let req = QueryAgentByOwnerRequest::new("owner_hash", 10, 0);
        let proto: proto::QueryAgentByOwnerRequest = req.into();
        assert_eq!(proto.owner_agent_hash, "owner_hash");
        assert_eq!(proto.limit, 10);
    }
}
